//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.Locale {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileApp.Locale.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have an account.
        /// </summary>
        public static string AccountHave {
            get {
                return ResourceManager.GetString("AccountHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can rate this advice.
        /// </summary>
        public static string CanRateAdvice {
            get {
                return ResourceManager.GetString("CanRateAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can rate this training.
        /// </summary>
        public static string CanRateTraining {
            get {
                return ResourceManager.GetString("CanRateTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid update attempt.
        /// </summary>
        public static string ChangeError {
            get {
                return ResourceManager.GetString("ChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change information.
        /// </summary>
        public static string ChangeInfo {
            get {
                return ResourceManager.GetString("ChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information has been updated.
        /// </summary>
        public static string ChangeSuccess {
            get {
                return ResourceManager.GetString("ChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count exercise lower bound.
        /// </summary>
        public static string CountLow {
            get {
                return ResourceManager.GetString("CountLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count exercise upper bound.
        /// </summary>
        public static string CountUp {
            get {
                return ResourceManager.GetString("CountUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string EnterFirstName {
            get {
                return ResourceManager.GetString("EnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add link to your image.
        /// </summary>
        public static string EnterImage {
            get {
                return ResourceManager.GetString("EnterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter yout second name.
        /// </summary>
        public static string EnterSecondName {
            get {
                return ResourceManager.GetString("EnterSecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        public static string EnterUsername {
            get {
                return ResourceManager.GetString("EnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name length should be between 2 and 40.
        /// </summary>
        public static string ErrorName {
            get {
                return ResourceManager.GetString("ErrorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} exercises.
        /// </summary>
        public static string Exercise {
            get {
                return ResourceManager.GetString("Exercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Url.
        /// </summary>
        public static string ImageUrl {
            get {
                return ResourceManager.GetString("ImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is incorrect.
        /// </summary>
        public static string IncorrectEmail {
            get {
                return ResourceManager.GetString("IncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Name.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating lower bound.
        /// </summary>
        public static string RatingLow {
            get {
                return ResourceManager.GetString("RatingLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating upper bound.
        /// </summary>
        public static string RatingUp {
            get {
                return ResourceManager.GetString("RatingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string RequiredFname {
            get {
                return ResourceManager.GetString("RequiredFname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name is required.
        /// </summary>
        public static string RequiredSname {
            get {
                return ResourceManager.GetString("RequiredSname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Name.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register.
        /// </summary>
        public static string UnableRegister {
            get {
                return ResourceManager.GetString("UnableRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have problem with this case.
        /// </summary>
        public static string VoiceError {
            get {
                return ResourceManager.GetString("VoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your voice.
        /// </summary>
        public static string VoiceSuccess {
            get {
                return ResourceManager.GetString("VoiceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} votes.
        /// </summary>
        public static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
    }
}
